### ISSUE TITLE
super slow

### ISSUE THREAD

**Issue by cybermagnetar** [AzizKpln/Moriarty-Project#62]
trust me bro this script is good i have gone through but the problem is that it is scrapping through everything that is not even needed.
 please make changes so that we can scrap according to our preferences and needs. i need to use this tool urgently.

**Comment by AzizKpln** [comment]
Hi again,
Please stop creating issues. You can check documentation page of this tool. You dont have to choose all the features. What you're asking is already in this tool. You don't have to choose all the features. You can choose the features that you're interested in.

For being slow,
This project is developed with requests, bs4 and playwright. Playwright might return the results a bit late. The reason is that playwright uses normal browser for scraping and this cause the slowness. I can't make this tool better. If you can, please open a pull request and i'll approve it.
